name: RSS

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
        
    env:
      TOKEN: ${{ secrets.TOKEN }}      

    steps:
    
    - uses: actions/checkout@v1
    - name: Whats around?
      run: ls
    - name: execution permissions
      run: chmod 755 ./build.sh
    - name: build
      run: ./build.sh
    - name: git bootstrap
      run: git config --global user.email "lbonanomi@gmail.com"
    - name: more
      run: git config --global user.name "lbonanomi RSS feeder"
    - name: git-add
      run: git add feed.xml
    - name: git-commit
      run: git commit -m "Autobuild"
    - name: git-push
      run: git push git push origin HEAD:master

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
